# Generated by Django 3.0.5 on 2025-11-21 09:39

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('code_matiere', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Code Matière')),
                ('nom_matiere', models.CharField(max_length=50, verbose_name='Nom de la Matière')),
                ('semestre', models.CharField(choices=[('S1', 'S1'), ('s2', 's2'), ('s3', 's3'), ('S4', 'S4'), ('s5', 's5'), ('s6', 's6')], max_length=20, verbose_name='semestre')),
                ('coef', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Coefficient')),
            ],
            options={
                'verbose_name': 'Matières',
                'verbose_name_plural': 'Matières',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('code_option', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Code option')),
                ('nom_option', models.CharField(max_length=20, verbose_name='Nom option')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Option',
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ue', models.CharField(max_length=20, unique=True, verbose_name='Code UE')),
                ('nom_ue', models.CharField(max_length=50, verbose_name="Nom de l'UE")),
                ('semestre', models.CharField(choices=[('S1', 'S1'), ('s2', 's2'), ('s3', 's3'), ('S4', 'S4'), ('s5', 's5'), ('s6', 's6')], max_length=20, verbose_name='semestre')),
            ],
            options={
                'verbose_name': "Unité d'Enseignement",
                'verbose_name_plural': "Unités d'Enseignement",
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_prof', models.CharField(max_length=20, unique=True, verbose_name='Code du Professeur')),
                ('matiere_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professeurs_principaux', to='Eleve.Matiere', verbose_name="Matière d'enseignement principale")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professeur', to=settings.AUTH_USER_MODEL, verbose_name='Compte Utilisateur')),
            ],
            options={
                'verbose_name': 'Professeur',
                'verbose_name_plural': 'Professeurs',
            },
        ),
        migrations.AddField(
            model_name='matiere',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres_ue', to='Eleve.UE', verbose_name="Unité d'Enseignement"),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('departement', models.CharField(choices=[('info', 'Informatique Génie Logiciel'), ('elec', 'Génie Électrique'), ('meca', 'Génie Mécanique')], default='info', max_length=50, verbose_name='Département')),
                ('option_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='Eleve.Option', verbose_name="Option/Classe de l'étudiant")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to=settings.AUTH_USER_MODEL, verbose_name='Compte Utilisateur')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
            },
        ),
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_seance', models.CharField(max_length=10, unique=True, verbose_name='ID Séance')),
                ('heure_debut', models.TimeField(verbose_name='Heure Début')),
                ('heure_fin', models.TimeField(verbose_name='Heure Fin')),
                ('date_seance', models.DateField(verbose_name='Date de la Séance')),
                ('jour_nom', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=10, verbose_name='Jour')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_matiere', to='Eleve.Matiere', verbose_name='Matière Enseignée')),
                ('option_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_classe', to='Eleve.Option', verbose_name='Option')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_professeur', to='Eleve.Professeur', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Emploi du Temps',
                'verbose_name_plural': 'Emplois du Temps',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Note CM')),
                ('coef_cm', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=4, verbose_name='Coef CM')),
                ('note_td', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Note TD')),
                ('coef_td', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=4, verbose_name='Coef TD')),
                ('note_tp', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Note TP')),
                ('coef_tp', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=4, verbose_name='Coef TP')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Eleve.Etudiant', verbose_name='Étudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Eleve.Matiere', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'unique_together': {('etudiant', 'matiere')},
            },
        ),
    ]
